title: Black Whole Coffee
email: info@blackwholecoffee.com
description: >-
  Minimalist, high-performance coffee. 
  Athens, Greece. Pre-orders only.
baseurl: "" # Keep this empty for custom domains
url: "https://www.blackwholecoffee.com"

timezone: Europe/Athens
remote_theme: jekyll/minima
